///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace gitTest
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the gitTestRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.0")]
    [RepositoryFolder("06315c6f-c6da-4d76-81f3-820e6d9a2a39")]
    public partial class gitTestRepository : RepoGenBaseFolder
    {
        static gitTestRepository instance = new gitTestRepository();
        gitTestRepositoryFolders.ExplorerAppFolder _explorer;
        gitTestRepositoryFolders.UltraVncClient105FrAppFolder _ultravncclient105fr;

        /// <summary>
        /// Gets the singleton class instance representing the gitTestRepository element repository.
        /// </summary>
        [RepositoryFolder("06315c6f-c6da-4d76-81f3-820e6d9a2a39")]
        public static gitTestRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public gitTestRepository() 
            : base("gitTestRepository", "/", null, 0, false, "06315c6f-c6da-4d76-81f3-820e6d9a2a39", ".\\RepositoryImages\\gitTestRepository06315c6f.rximgres")
        {
            _explorer = new gitTestRepositoryFolders.ExplorerAppFolder(this);
            _ultravncclient105fr = new gitTestRepositoryFolders.UltraVncClient105FrAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("06315c6f-c6da-4d76-81f3-820e6d9a2a39")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The Explorer folder.
        /// </summary>
        [RepositoryFolder("75711665-5072-4eef-9d47-a46c6a419bb9")]
        public virtual gitTestRepositoryFolders.ExplorerAppFolder Explorer
        {
            get { return _explorer; }
        }

        /// <summary>
        /// The UltraVncClient105Fr folder.
        /// </summary>
        [RepositoryFolder("204cb319-6b9b-411e-929a-8fe7e778023d")]
        public virtual gitTestRepositoryFolders.UltraVncClient105FrAppFolder UltraVncClient105Fr
        {
            get { return _ultravncclient105fr; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.0")]
    public partial class gitTestRepositoryFolders
    {
        /// <summary>
        /// The ExplorerAppFolder folder.
        /// </summary>
        [RepositoryFolder("75711665-5072-4eef-9d47-a46c6a419bb9")]
        public partial class ExplorerAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _ultravncclient105frInfo;

            /// <summary>
            /// Creates a new Explorer  folder.
            /// </summary>
            public ExplorerAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Explorer", "/desktop[@processname='explorer']", parentFolder, 30000, null, true, "75711665-5072-4eef-9d47-a46c6a419bb9", "")
            {
                _ultravncclient105frInfo = new RepoItemInfo(this, "UltraVncClient105Fr", "?/?/list[@controlid='1']/listitem[@text='UltraVnc-Client-105-Fr']", 30000, null, "6bc13b7f-97f7-49c0-bcb7-a4ee9b33f4cb");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("75711665-5072-4eef-9d47-a46c6a419bb9")]
            public virtual Ranorex.Desktop Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Desktop>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("75711665-5072-4eef-9d47-a46c6a419bb9")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The UltraVncClient105Fr item.
            /// </summary>
            [RepositoryItem("6bc13b7f-97f7-49c0-bcb7-a4ee9b33f4cb")]
            public virtual Ranorex.ListItem UltraVncClient105Fr
            {
                get
                {
                    return _ultravncclient105frInfo.CreateAdapter<Ranorex.ListItem>(true);
                }
            }

            /// <summary>
            /// The UltraVncClient105Fr item info.
            /// </summary>
            [RepositoryItemInfo("6bc13b7f-97f7-49c0-bcb7-a4ee9b33f4cb")]
            public virtual RepoItemInfo UltraVncClient105FrInfo
            {
                get
                {
                    return _ultravncclient105frInfo;
                }
            }
        }

        /// <summary>
        /// The UltraVncClient105FrAppFolder folder.
        /// </summary>
        [RepositoryFolder("204cb319-6b9b-411e-929a-8fe7e778023d")]
        public partial class UltraVncClient105FrAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _systemitemnamedisplayInfo;
            RepoItemInfo _fermerInfo;

            /// <summary>
            /// Creates a new UltraVncClient105Fr  folder.
            /// </summary>
            public UltraVncClient105FrAppFolder(RepoGenBaseFolder parentFolder) :
                    base("UltraVncClient105Fr", "/form[@title='UltraVnc-Client-105-Fr']", parentFolder, 30000, null, true, "204cb319-6b9b-411e-929a-8fe7e778023d", "")
            {
                _systemitemnamedisplayInfo = new RepoItemInfo(this, "SystemItemNameDisplay", ".//element[@instance='1']/container[@caption='ShellView']/?/?/listitem[@automationid='0']/text[@automationid='System.ItemNameDisplay']", 30000, null, "4d4c1991-1572-43cb-b191-f9833aee0dc0");
                _fermerInfo = new RepoItemInfo(this, "Fermer", "?/?/button[@accessiblename='Fermer']", 30000, null, "a62bc525-5a5d-4d66-91f2-9b404dcf2b9e");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("204cb319-6b9b-411e-929a-8fe7e778023d")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("204cb319-6b9b-411e-929a-8fe7e778023d")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The SystemItemNameDisplay item.
            /// </summary>
            [RepositoryItem("4d4c1991-1572-43cb-b191-f9833aee0dc0")]
            public virtual Ranorex.Text SystemItemNameDisplay
            {
                get
                {
                    return _systemitemnamedisplayInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The SystemItemNameDisplay item info.
            /// </summary>
            [RepositoryItemInfo("4d4c1991-1572-43cb-b191-f9833aee0dc0")]
            public virtual RepoItemInfo SystemItemNameDisplayInfo
            {
                get
                {
                    return _systemitemnamedisplayInfo;
                }
            }

            /// <summary>
            /// The Fermer item.
            /// </summary>
            [RepositoryItem("a62bc525-5a5d-4d66-91f2-9b404dcf2b9e")]
            public virtual Ranorex.Button Fermer
            {
                get
                {
                    return _fermerInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Fermer item info.
            /// </summary>
            [RepositoryItemInfo("a62bc525-5a5d-4d66-91f2-9b404dcf2b9e")]
            public virtual RepoItemInfo FermerInfo
            {
                get
                {
                    return _fermerInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}